name: confy
description: A yaml confiuration loader.
version: 1.0.0+1
homepage: https://github.com/0xWaleed/confy

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  yaml: ^3.1.0
